---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yo114.
--- DateTime: 22.02.2024 16:35
---
local SendOrderBuy = {}
SendOrderBuy.ACTION = 'NEW_ORDER'
SendOrderBuy.SECCODE = 'SBER'
SendOrderBuy.OPERATION = 'B'
SendOrderBuy.PRICE = '120'
SendOrderBuy.QUANTITY = '100'

print(SendOrderBuy.ACTION)