---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yo114.
--- DateTime: 22.02.2024 20:38
---
function SMA(Table, n)
    local TableSMA = {}
    for i = 1, #Table, 1 do
        if i < n then
            TableSMA[i] = Table[i]
        else
            local j = i
            local Sum = 0
            while j > i - n do
                Sum = Sum + Table[j]
                j = j - 1
            end
            TableSMA[i] = Sum/n
        end
    end
    return TableSMA
end

local TickerTable = {}
local DateTable = {}
local TimeTable = {}
local OpenTable = {}
local HighTable = {}
local LowTable = {}
local CloseTable = {}
local FileName = 'C:\\projects\\lua_demo\\brant.txt'
local FileRead
local StopRead = true

FileRead = io.open(FileName, 'r')

--print(Ticker, Date, Time, Open, High, Low, Close)

local i = 1
while StopRead == true do
    local Ticker, Date, Time, Open, High, Low, Close = FileRead:read(5,'*n','*n','*n','*n','*n','*n')
    if Date == nil then StopRead = false
    else
        TickerTable[i] = Ticker
        DateTable[i] = Date
        TimeTable[i] = Time
        OpenTable[i] = Open
        HighTable[i] = High
        LowTable[i] = Low
        CloseTable[i] = Close
        i = i + 1
    end
end

local FastSMA_N = 10
local SlowSMA_N = 50
local FastSMA = {}
local SlowSMA = {}

FastSMA = SMA(CloseTable, FastSMA_N)
SlowSMA = SMA(CloseTable, SlowSMA_N)
for j = 1, #TickerTable do
    print(TickerTable[j],
DateTable[j],TimeTable[j],OpenTable[j],HighTable[j],LowTable[j],CloseTable[j], FastSMA[j], SlowSMA[j])
end