---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yo114.
--- DateTime: 25.02.2024 22:50
---

function main()
    local TableRTS = AllocTable()
    AddColumn(TableRTS, 1, 'Legend', true, QTABLE_STRING_TYPE, 15)
    AddColumn(TableRTS, 2, 'Year', true, QTABLE_INT_TYPE, 10)
    AddColumn(TableRTS, 3, 'Month', true, QTABLE_INT_TYPE, 13)
    AddColumn(TableRTS, 4, 'Day', true, QTABLE_INT_TYPE, 10)
    AddColumn(TableRTS, 5, 'Hour', true, QTABLE_INT_TYPE, 10)
    AddColumn(TableRTS, 6, 'Minute', true, QTABLE_INT_TYPE, 10)
    AddColumn(TableRTS, 7, 'Seconds', true, QTABLE_INT_TYPE, 13)
    AddColumn(TableRTS, 8, 'Open', true, QTABLE_INT_TYPE, 13)
    AddColumn(TableRTS, 9, 'Max', true, QTABLE_INT_TYPE, 13)
    AddColumn(TableRTS, 10, 'Min', true, QTABLE_INT_TYPE, 13)
    AddColumn(TableRTS, 11, 'Close', true, QTABLE_INT_TYPE, 13)
    AddColumn(TableRTS, 12, 'Vol', true, QTABLE_INT_TYPE, 10)
    AddColumn(TableRTS, 13, 'Max N', true, QTABLE_INT_TYPE, 10)
    AddColumn(TableRTS, 14, 'Min N', true, QTABLE_INT_TYPE, 10)
    CreateWindow(TableRTS)
    SetWindowCaption(TableRTS, 'Graphics info RTS')
    SetWindowPos(TableRTS, 0,0,1100,100)
    InsertRow(TableRTS, -1)

    local RTSPrice = CreateDataSource('SPBFUT', 'SiH4', INTERVAL_H1)
    local RTSN = RTSPrice:Size()
    local Year = RTSPrice:T(RTSN).year
    local Month = RTSPrice:T(RTSN).month
    local Day = RTSPrice:T(RTSN).day
    local Hour = RTSPrice:T(RTSN).hour
    local Min = RTSPrice:T(RTSN).min
    local Sec = RTSPrice:T(RTSN).sec
    local Open = RTSPrice:O(RTSN)
    local High = RTSPrice:H(RTSN)
    local Low = RTSPrice:L(RTSN)
    local Close = RTSPrice:C(RTSN)
    local Vol = RTSPrice:V(RTSN)
    local MaxN = 0
    local MinN = Low
    local N = 200
    local j = RTSN
    while j >= RTSN-N do
        if RTSPrice:H(j) > MaxN then
            MaxN = RTSPrice:H(j)
        end
        if RTSPrice:L(j) < MinN then
            MinN = RTSPrice:L(j)
        end
        j=j-1
    end

    SetCell(TableRTS, 1,1, tostring('RTSName'))
    SetCell(TableRTS, 1,2, tostring(Year))
    SetCell(TableRTS, 1,3, tostring(Month))
    SetCell(TableRTS, 1,4, tostring(Day))
    SetCell(TableRTS, 1,5, tostring(Hour))
    SetCell(TableRTS, 1,6, tostring(Min))
    SetCell(TableRTS, 1,7, tostring(Sec))
    SetCell(TableRTS, 1,8, tostring(Open-Open%1))
    SetCell(TableRTS, 1,9, tostring(High-High%1))
    SetCell(TableRTS, 1,10, tostring(Low-Low%1))
    SetCell(TableRTS, 1,11, tostring(Close-Close%1))
    SetCell(TableRTS, 1,12, tostring(Vol))
    SetCell(TableRTS, 1,13, tostring(MaxN))
    SetCell(TableRTS, 1,14, tostring(MinN))
end