---
--- Generated by Luanalysis
--- Created by lette.
--- DateTime: 27.02.2024 23:15
---
local stopped = false
function OnStop()
    stopped = true
    return 5000
end

FIRM_ID = 'SPBFUT000000'
ACCOUNT = 'SPBFUT000zt'
CLIENT_CODE = 'SPBFUT000zt'
CLASS_CODE = 'SPBFUT'
SEC_CODE = 'SiH4'

function main()
    local PriceRTSBuy = getParamEx(CLASS_CODE, SEC_CODE, "LAST").param_value
    local LimitOrderBuy = {
        ["ACTION"] = "NEW_ORDER",
        ["ACCOUNT"] = ACCOUNT,
        ["OPERATION"] = "B",
        ["CLASSCODE"] = CLASS_CODE,
        ["SECCODE"] = SEC_CODE,
        ["PRICE"] = tostring(PriceRTSBuy),
        ["QUANTITY"] = tostring(1),
        ["TRANS_ID"] = tostring(1)
    }
    local Err_Order = sendTransaction(LimitOrderBuy)
end

